server:
  port: 9002
spring:
  application:
    name: apespace_recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apespace_recruit?characterEncoding=utf-8
    password: root
    username: root
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
