server:
  port: 9007
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    name: apespace_spitslot
  data:
    mongodb:
      host: 192.168.146.20
      database: spitslot
  redis:
    host: 192.168.146.20